import { VFC } from 'react';
import Head from 'next/head';
import { AppProps } from 'next/app';

import 'src/styles/globals.css';

const MyApp: VFC = ({ Component, pageProps }: AppProps) => {
	return (
		<>
			<Head>
				<title>divlog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Component {...pageProps} />
		</>
	);
};

export default MyApp;
